
STATUS_EFFECT_PLUS_DEFENSE_VAL = 3

STATUS_EFFECT_PLUS_SPEED_VAL = 1
STATUS_EFFECT_SLOW_ON_HIT_VAL = 3

STATUS_EFFECT_CHILL_ON_HIT_VAL = 2

"""Potion Stuff"""
POTION_SMALL_HEAL_VAL = 3
POTION_SMALL_HEAL_DURATION = 4

POTION_MED_HEAL_VAL = 5
POTION_MED_HEAL_DURATION = 4

POTION_POIS_VAL = 2
POTION_POIS_DURATION = 4

POTION_NIGHT_VISION_VAL = 2
POTION_NIGHT_VISION_DURATION = 15

POTION_SPEED_VAL = 2
POTION_SPEED_DUR = 6

POTION_SLOW_VAL = 3
POTION_SLOW_DUR = 4

POTION_NULLIFICATION_DURATION = 7
POTION_CONFUSION_DURATION = 8

"""Enemy AI Stuff"""
ENEMY_SMART_PATHING_RANGE = 8
ENEMY_PATHING_SKILL = (0.0, 0.7, 0.95, 0.95, 1.0)  # value for each level of intelligence
CONFUSION_CHANCE = 0.75

ENEMY_ITEM_CHANCE_PER_WEALTH = 0.5

CHEST_MIN_NUM_ITEMS = 1
CHEST_MAX_NUM_ITEMS = 3
CHEST_DROP_RATE = 0.4

"""Drop Rates by Item Type"""
STAT_CUBE_5_DROP_RATE = 100
STAT_CUBE_6_DROP_RATE = 50
STAT_CUBE_7_DROP_RATE = 20
WEAPON_DROP_RATE = 30
POTION_DROP_RATE = 50
FISHING_ROD_DROP_RATE = 2

"""Item Gen Stuff"""
STAT_CUBE_5_MAX_NUM_STATS = 1
STAT_CUBE_6_MAX_NUM_STATS = 2
STAT_CUBE_7_MAX_NUM_STATS = 3


def max_stats_for_n_cubes(n_cubes):
    if n_cubes <= 5:
        return STAT_CUBE_5_MAX_NUM_STATS
    elif n_cubes == 6:
        return STAT_CUBE_6_MAX_NUM_STATS
    else:
        return STAT_CUBE_7_MAX_NUM_STATS
