
STATUS_EFFECT_PLUS_DEFENSE_VAL = 3

STATUS_EFFECT_PLUS_SPEED_VAL = 1

"""Potion Stuff"""
POTION_SMALL_HEAL_VAL = 3
POTION_SMALL_HEAL_DURATION = 4

POTION_MED_HEAL_VAL = 5
POTION_MED_HEAL_DURATION = 4

POTION_POIS_VAL = 2
POTION_POIS_DURATION = 4

POTION_NIGHT_VISION_VAL = 2
POTION_NIGHT_VISION_DURATION = 15

POTION_SPEED_VAL = 2
POTION_SPEED_DUR = 6

POTION_SLOW_VAL = -3
POTION_SLOW_DUR = 4

POTION_NULLIFICATION_DURATION = 7
POTION_CONFUSION_DURATION = 8

"""Enemy AI Stuff"""
ENEMY_SMART_PATHING_RANGE = 8
ENEMY_PATHING_SKILL = (0.0, 0.7, 0.95, 0.95, 0.95)  # value for each level of intelligence
CONFUSION_CHANCE = 0.75

"""Drop Rate Stuff"""
ENEMY_ITEM_CHANCE_PER_WEALTH = 0.6

CHEST_MIN_NUM_ITEMS = 1
CHEST_MAX_NUM_ITEMS = 3
CHEST_DROP_RATE = 0.4

STAT_CUBE_5_DROP_RATE = 10
STAT_CUBE_6_DROP_RATE = 5
STAT_CUBE_7_DROP_RATE = 2
WEAPON_DROP_RATE = 5
POTION_DROP_RATE = 7
