from enum import Enum


class PlayerStatType(Enum):
    HP = "HP",
    DPS = "DPS",
    MOVESPEED = "MOVE_SPEED",
    TICKS_PER_ATTACK = "TICKS_PER_ATTACK",
    ATTACK_RADIUS = "ATTACK_RADIUS",


class StatType(Enum):
    ATT = "ATT",
    DEF = "DEF",
    VIT = "VIT",
    ATTACK_RADIUS = "ATTACK_RADIUS",
    ATTACK_SPEED = "ATTACK_SPEED",
    ATTACK_DAMAGE= "ATTACK_DAMAGE",
    MOVEMENT_SPEED = "MOVEMENT_SPEED",
    DODGE = "DODGE",
    ACCURACY = "ACCURACY",
    LIFE_REGEN = "LIFE_REGEN",
    LIFE_ON_HIT = "LIFE_ON_HIT",
    LIFE_LEECH = "LIFE_LEECH",
    MAX_HEALTH = "MAX_HEALTH",
    POTION_HEALING = "POTION_HEALING",
    POTION_COOLDOWN = "POTION_COOLDOWN",

    HOLE_BONUS = "HOLE_BONUS"